# To build what is need

before_install:
  # 安装 XeTeX
  - sudo apt-get install -y --no-install-recommends wget texlive-base texlive-xetex latex-xcolor
  - sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra lmodern exlive-latex-recommended
  - cd ~ && mkdir texmf
  - tlmgr init-usertree
  - sudo tlmgr update --all
  - sudo tlmgr install ctex l3kernel xecjk l3packages latex
  - sudo tlmgr install geometry fontspec fandol ulem zhnumber
  - cd $TRAVIS_BUILD_DIR

script: # 重要的东西编译三遍
  - wget https://raw.githubusercontent.com/DingoLab/dingo.tex/master/dingo.cls
  - wget https://raw.githubusercontent.com/DingoLab/dingo.tex/master/geometry.sty
  - wget https://raw.githubusercontent.com/DingoLab/dingo.tex/master/geometry.cfg
  - xelatex API.tex
  - xelatex API.tex
  - xelatex API.tex
  - xelatex Plan.tex
  - xelatex Plan.tex
  - xelatex Plan.tex
  - echo "DONE"

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    git config --global user.name "travis_auto"
    git config --global user.email "qinka@live.com"
    cd ~
    git clone https://qinka:$GITHUB_API_KEY@github.com/DingoLab/DingoRelease.git
    cd DingoRelease
    export RELPATH=$(pwd)
    cp "$TRAVIS_BUILD_DIR"/*.pdf .
    git add .
    git commit -am"travis-ci $(date)"
    git push origin master
    cd ~
    sudo rm -rf $RELPATH
    cd "$TRAVIS_BUILD_DIR"
  fi
